#!/bin/bash
EMAIL=$(git config user.email)
if [[ $EMAIL == *"@gmail.com"* ]]; then
	echo "[INFO] Verified email: $EMAIL"
else
	echo "[ERROR] Invalid email: $EMAIL => Please configure the company email and retry."
	echo "Steps:"
	echo "   cd $PWD"
	echo '   git config user.email "kimminji.dev@gmail.com"'
	echo ""
	exit 1
fi
